// lib/n8n/workflow-registry.ts
// N3 Empire OS - 神経系ワークフローレジストリ

export type WorkflowStatus = 'active' | 'partial' | 'planned' | 'deprecated';
export type WorkflowCategory = 'listing' | 'inventory' | 'research' | 'pricing' | 'orders' | 'shipping' | 'sync' | 'ai' | 'media' | 'translation' | 'defense' | 'command' | 'finance' | 'notification' | 'system' | 'module';
export type TechStack = 'n8n' | 'python' | 'typescript' | 'sql' | 'shell';
export type AIComponent = 'claude' | 'gemini' | 'gpt4' | 'elevenlabs' | 'midjourney' | 'whisper' | 'none';

export interface WorkflowNode {
  id: string; name: string; nameJp: string; description: string; category: WorkflowCategory; status: WorkflowStatus;
  techStack: TechStack[]; aiComponents: AIComponent[]; hasUI: boolean; hasAPI: boolean; hasDB: boolean;
  webhookPath?: string; n8nWorkflowId?: string; dependencies: string[]; triggers: string[];
  simpleExplain?: string; whenRuns?: string; whatHappens?: string; logic?: string;
  selfHealing?: boolean; autoApproval?: boolean; pythonScripts?: string[];
}

export interface PythonScript { id: string; name: string; description: string; }

export const CATEGORY_CONFIG: Record<WorkflowCategory, { icon: string; color: string; label: string }> = {
  listing: { icon: '📦', color: '#10b981', label: '出品' },
  inventory: { icon: '📊', color: '#3b82f6', label: '在庫' },
  research: { icon: '🔍', color: '#8b5cf6', label: 'リサーチ' },
  pricing: { icon: '💰', color: '#f59e0b', label: '価格' },
  orders: { icon: '📋', color: '#ec4899', label: '注文' },
  shipping: { icon: '🚚', color: '#06b6d4', label: '配送' },
  sync: { icon: '🔄', color: '#6366f1', label: '同期' },
  ai: { icon: '🤖', color: '#14b8a6', label: 'AI' },
  media: { icon: '🎬', color: '#f97316', label: 'メディア' },
  translation: { icon: '🌐', color: '#0ea5e9', label: '翻訳' },
  defense: { icon: '🛡️', color: '#ef4444', label: '防衛' },
  command: { icon: '🎯', color: '#a855f7', label: '司令塔' },
  finance: { icon: '💵', color: '#22c55e', label: '財務' },
  notification: { icon: '🔔', color: '#eab308', label: '通知' },
  system: { icon: '⚙️', color: '#6b7280', label: 'システム' },
  module: { icon: '🧩', color: '#78716c', label: 'モジュール' },
};

export const PYTHON_SCRIPTS: PythonScript[] = [
  { id: 'image-washer', name: 'image_washer.py', description: 'AI画像指紋消し' },
  { id: 'pdf-parser', name: 'pdf_parser.py', description: 'PDF過去問抽出' },
  { id: 'lip-sync', name: 'lip_sync.py', description: 'リップシンクデータ生成' },
  { id: 'competitor-scraper', name: 'competitor_scraper.py', description: '競合スクレイピング' },
  { id: 'hts-classifier', name: 'hts_classifier.py', description: 'HTS関税コード分類' },
  { id: 'psa-grader', name: 'psa_grader.py', description: 'PSAグレード予測' },
  { id: 'video-render', name: 'video_render.py', description: '動画レンダリング' },
  { id: 'ocr-engine', name: 'ocr_engine.py', description: '日本語OCR' },
];

export const WORKFLOW_REGISTRY: WorkflowNode[] = [
  // === 出品 (listing) - 20件 ===
  { id: 'listing-reserve', name: 'listing-reserve', nameJp: '📦 出品予約', description: '選択商品をeBay/Amazonに出品予約', category: 'listing', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/listing-reserve', dependencies: ['notify-chatwork'], triggers: ['schedule-cron'], simpleExplain: '商品を選んで出品ボタンを押すとeBayに自動登録', selfHealing: true },
  { id: 'listing-batch', name: 'listing-batch', nameJp: '📦 バッチ出品', description: '大量商品を一括出品', category: 'listing', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/listing-batch', dependencies: ['listing-reserve'], triggers: [], simpleExplain: '100件以上の商品を一気に出品' },
  { id: 'listing-relist', name: 'listing-relist', nameJp: '🔁 再出品', description: '売れなかった商品を自動再出品', category: 'listing', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/listing-relist', dependencies: [], triggers: ['schedule-cron'], simpleExplain: '売れなかった商品を自動で再出品', selfHealing: true, autoApproval: true },
  { id: 'listing-end', name: 'listing-end', nameJp: '⏹️ 出品終了', description: '商品の出品を終了', category: 'listing', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/listing-end', dependencies: [], triggers: [], simpleExplain: '出品をやめたい商品をeBayから取り下げ' },
  { id: 'listing-revise-price', name: 'listing-revise-price', nameJp: '💵 価格変更', description: '出品中商品の価格を変更', category: 'listing', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/listing-revise-price', dependencies: [], triggers: ['pricing-dynamic'], simpleExplain: 'eBayの商品の値段を変える' },
  { id: 'listing-revise-quantity', name: 'listing-revise-quantity', nameJp: '📊 数量変更', description: '出品中商品の在庫数を変更', category: 'listing', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/listing-revise-quantity', dependencies: [], triggers: ['inventory-sync-all'], simpleExplain: 'eBayの在庫数を変える' },
  { id: 'listing-draft', name: 'listing-draft', nameJp: '📝 下書き保存', description: '出品前の下書き保存', category: 'listing', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/listing-draft', dependencies: [], triggers: [], simpleExplain: '出品前にとりあえず保存' },
  { id: 'listing-bulk-edit', name: 'listing-bulk-edit', nameJp: '✏️ 一括編集', description: '複数商品を一括変更', category: 'listing', status: 'partial', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/listing-bulk-edit', dependencies: [], triggers: [], simpleExplain: '100件の商品をまとめて編集' },
  { id: 'listing-clone', name: 'listing-clone', nameJp: '📋 出品コピー', description: '既存出品をコピーして新規作成', category: 'listing', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/listing-clone', dependencies: [], triggers: [], simpleExplain: '似た商品を出すとき設定をコピー' },
  { id: 'listing-template-apply', name: 'listing-template-apply', nameJp: '📑 テンプレ適用', description: '出品テンプレートを商品に適用', category: 'listing', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/listing-template', dependencies: [], triggers: [], simpleExplain: 'ポケカ用テンプレを当てる' },
  { id: 'listing-schedule', name: 'listing-schedule', nameJp: '⏰ 出品予約（時間指定）', description: '指定日時に出品開始', category: 'listing', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/listing-schedule', dependencies: ['listing-reserve'], triggers: ['schedule-cron'], simpleExplain: '日曜夜9時に出品開始を設定' },
  { id: 'listing-category-suggest', name: 'listing-category-suggest', nameJp: '🏷️ カテゴリ提案', description: 'AI/APIでeBayカテゴリを自動提案', category: 'listing', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['gemini'], hasUI: true, hasAPI: true, hasDB: false, webhookPath: '/webhook/listing-category', dependencies: [], triggers: [], simpleExplain: 'これ何カテゴリ？をAIが教える' },
  { id: 'listing-specifics-fill', name: 'listing-specifics-fill', nameJp: '📝 Item Specifics自動入力', description: 'AIでItem Specificsを自動埋め', category: 'listing', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['claude', 'gemini'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/listing-specifics', dependencies: [], triggers: ['listing-reserve'], simpleExplain: 'ブランド/サイズを自動で埋める' },
  { id: 'listing-variation-create', name: 'listing-variation-create', nameJp: '🎨 バリエーション作成', description: '色/サイズ違いのバリエーション出品', category: 'listing', status: 'partial', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/listing-variation', dependencies: [], triggers: [], simpleExplain: '赤・青・黒の色違いを1出品にまとめる' },
  { id: 'listing-amazon-sync', name: 'listing-amazon-sync', nameJp: '🛒 Amazon同時出品', description: 'eBay出品をAmazonにも展開', category: 'listing', status: 'planned', techStack: ['n8n', 'python'], aiComponents: ['none'], hasUI: false, hasAPI: false, hasDB: true, webhookPath: '/webhook/listing-amazon', dependencies: [], triggers: ['listing-reserve'], simpleExplain: 'eBayに出したらAmazonにも自動出品' },
  { id: 'listing-image-process', name: 'listing-image-process', nameJp: '🖼️ 画像処理', description: '出品画像のリサイズ/背景除去', category: 'listing', status: 'active', techStack: ['n8n', 'python'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: false, webhookPath: '/webhook/listing-image', dependencies: [], triggers: ['listing-reserve'], simpleExplain: '画像を出品用にキレイに加工', pythonScripts: ['image_washer.py'] },
  { id: 'listing-title-optimize', name: 'listing-title-optimize', nameJp: '✨ タイトル最適化', description: 'AIでSEO最適なタイトル生成', category: 'listing', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['claude', 'gemini'], hasUI: true, hasAPI: true, hasDB: false, webhookPath: '/webhook/listing-title', dependencies: [], triggers: [], simpleExplain: 'AIが売れるタイトルを考える' },
  { id: 'listing-description-generate', name: 'listing-description-generate', nameJp: '📝 説明文生成', description: 'AIで魅力的な説明文を自動生成', category: 'listing', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['claude'], hasUI: true, hasAPI: true, hasDB: false, webhookPath: '/webhook/listing-description', dependencies: [], triggers: [], simpleExplain: 'AIが商品の説明文を書く' },
  { id: 'listing-policy-assign', name: 'listing-policy-assign', nameJp: '📋 ポリシー割当', description: 'Business Policyを商品に自動割当', category: 'listing', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/listing-policy', dependencies: [], triggers: ['listing-reserve'], simpleExplain: '配送方法や支払い方法を自動設定' },
  { id: 'listing-mercari-sync', name: 'listing-mercari-sync', nameJp: '🛍️ メルカリ同時出品', description: 'メルカリにも同時出品', category: 'listing', status: 'planned', techStack: ['n8n', 'python'], aiComponents: ['none'], hasUI: false, hasAPI: false, hasDB: true, webhookPath: '/webhook/listing-mercari', dependencies: [], triggers: ['listing-reserve'], simpleExplain: 'eBayに出したらメルカリにも自動出品' },

  // === 在庫 (inventory) - 15件 ===
  { id: 'inventory-sync-all', name: 'inventory-sync-all', nameJp: '🔄 全在庫同期', description: '全マーケットプレイスの在庫を一括同期', category: 'inventory', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/inventory-sync', dependencies: ['listing-revise-quantity'], triggers: ['schedule-cron'], simpleExplain: 'eBay/Amazon/全部の在庫数を揃える', selfHealing: true },
  { id: 'inventory-monitoring', name: 'inventory-monitoring', nameJp: '👁️ 在庫監視', description: '仕入先の在庫状況をスクレイピング監視', category: 'inventory', status: 'active', techStack: ['n8n', 'python'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/inventory-monitoring', dependencies: ['notify-chatwork'], triggers: ['schedule-cron'], simpleExplain: '仕入先サイトを見張って売り切れを検知', pythonScripts: ['competitor_scraper.py'], selfHealing: true },
  { id: 'inventory-check-stock', name: 'inventory-check-stock', nameJp: '🔍 在庫確認', description: '選択商品の在庫状況を即時確認', category: 'inventory', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/inventory-check', dependencies: [], triggers: [], simpleExplain: '今すぐ在庫があるかチェック' },
  { id: 'inventory-alert-low', name: 'inventory-alert-low', nameJp: '⚠️ 在庫少アラート', description: '在庫が閾値以下になったら通知', category: 'inventory', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: false, hasAPI: true, hasDB: true, webhookPath: '/webhook/inventory-alert', dependencies: ['notify-chatwork'], triggers: ['inventory-monitoring'], simpleExplain: '在庫残り3個！みたいな通知が来る', autoApproval: true },
  { id: 'inventory-auto-delist', name: 'inventory-auto-delist', nameJp: '🚫 自動取り下げ', description: '在庫切れ商品を自動で出品停止', category: 'inventory', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: false, hasAPI: true, hasDB: true, webhookPath: '/webhook/inventory-delist', dependencies: ['listing-end'], triggers: ['inventory-monitoring'], simpleExplain: '在庫0になったら自動で出品を止める', autoApproval: true, selfHealing: true },
  { id: 'inventory-auto-relist', name: 'inventory-auto-relist', nameJp: '♻️ 自動再出品', description: '在庫復活した商品を自動再出品', category: 'inventory', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: false, hasAPI: true, hasDB: true, webhookPath: '/webhook/inventory-auto-relist', dependencies: ['listing-reserve'], triggers: ['inventory-monitoring'], simpleExplain: '在庫が戻ったら自動で再出品', autoApproval: true },
  { id: 'inventory-bundle-adjust', name: 'inventory-bundle-adjust', nameJp: '📦 バンドル在庫調整', description: 'セット商品売れたら単品在庫も減らす', category: 'inventory', status: 'partial', techStack: ['n8n', 'sql'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/inventory-bundle', dependencies: [], triggers: ['orders-new'], simpleExplain: '3枚セットが売れたら単品在庫も3個減る' },
  { id: 'inventory-location-track', name: 'inventory-location-track', nameJp: '📍 ロケーション追跡', description: '倉庫内のどこに商品があるか管理', category: 'inventory', status: 'partial', techStack: ['n8n', 'sql'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/inventory-location', dependencies: [], triggers: [], simpleExplain: 'この商品は棚Aの3段目みたいな場所を記録' },
  { id: 'inventory-reorder-suggest', name: 'inventory-reorder-suggest', nameJp: '🛒 発注提案', description: '在庫少の商品を発注提案', category: 'inventory', status: 'planned', techStack: ['n8n'], aiComponents: ['gemini'], hasUI: false, hasAPI: true, hasDB: true, webhookPath: '/webhook/inventory-reorder', dependencies: ['notify-chatwork'], triggers: ['schedule-cron'], simpleExplain: 'この商品そろそろ発注しては？と教える' },
  { id: 'inventory-cost-update', name: 'inventory-cost-update', nameJp: '💰 原価更新', description: '仕入原価の更新と利益再計算', category: 'inventory', status: 'active', techStack: ['n8n', 'sql'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/inventory-cost', dependencies: ['pricing-profit-calc'], triggers: [], simpleExplain: '仕入れ値が変わったとき、利益も再計算' },
  { id: 'inventory-import-csv', name: 'inventory-import-csv', nameJp: '📥 CSV一括登録', description: 'CSVファイルから在庫を一括登録', category: 'inventory', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/inventory-import', dependencies: [], triggers: [], simpleExplain: 'Excelで作った商品リストを一括登録' },
  { id: 'inventory-export-csv', name: 'inventory-export-csv', nameJp: '📤 CSV出力', description: '在庫一覧をCSVでエクスポート', category: 'inventory', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/inventory-export', dependencies: [], triggers: [], simpleExplain: '在庫リストをExcel用にダウンロード' },
  { id: 'inventory-dead-stock', name: 'inventory-dead-stock', nameJp: '💀 デッドストック検出', description: '長期間売れない商品を検出', category: 'inventory', status: 'partial', techStack: ['n8n', 'sql'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/inventory-dead', dependencies: ['notify-chatwork'], triggers: ['schedule-cron'], simpleExplain: '90日以上売れてない商品を見つける' },
  { id: 'inventory-audit', name: 'inventory-audit', nameJp: '📋 棚卸し', description: '実在庫とシステム在庫の照合', category: 'inventory', status: 'partial', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/inventory-audit', dependencies: [], triggers: [], simpleExplain: '実際の在庫とシステムの数が合ってるかチェック' },

  // === 価格 (pricing) - 12件 ===
  { id: 'pricing-profit-calc', name: 'pricing-profit-calc', nameJp: '💰 利益計算', description: '販売価格から利益を自動計算', category: 'pricing', status: 'active', techStack: ['n8n', 'typescript', 'sql'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/pricing-profit', dependencies: [], triggers: ['listing-reserve'], simpleExplain: '売値を入れるといくら儲かるか自動計算', logic: '売価 - 原価 - 手数料 - 送料 = 利益' },
  { id: 'pricing-fee-calc', name: 'pricing-fee-calc', nameJp: '📊 手数料計算', description: 'eBay/PayPal/その他の手数料を計算', category: 'pricing', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: false, webhookPath: '/webhook/pricing-fee', dependencies: [], triggers: ['pricing-profit-calc'], simpleExplain: 'eBayとPayPalに取られる手数料を計算' },
  { id: 'pricing-shipping-calc', name: 'pricing-shipping-calc', nameJp: '🚚 送料計算', description: '重量/サイズから送料を自動計算', category: 'pricing', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/pricing-shipping', dependencies: [], triggers: ['pricing-profit-calc'], simpleExplain: '重さとサイズから送料を計算' },
  { id: 'pricing-tariff-calc', name: 'pricing-tariff-calc', nameJp: '🏛️ 関税計算', description: 'HTSコードから関税を計算', category: 'pricing', status: 'active', techStack: ['n8n', 'python'], aiComponents: ['gemini'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/pricing-tariff', dependencies: [], triggers: [], simpleExplain: 'アメリカに送るとき関税がいくらかかるか計算', pythonScripts: ['hts_classifier.py'] },
  { id: 'pricing-dynamic', name: 'pricing-dynamic', nameJp: '📈 動的価格調整', description: '需要/在庫に応じて価格を自動調整', category: 'pricing', status: 'partial', techStack: ['n8n', 'typescript'], aiComponents: ['gemini'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/pricing-dynamic', dependencies: ['listing-revise-price'], triggers: ['schedule-cron'], simpleExplain: '売れ行きに応じて自動で値段を上げ下げ' },
  { id: 'pricing-competitor', name: 'pricing-competitor', nameJp: '🔍 競合価格追跡', description: '競合の価格を監視して自動追従', category: 'pricing', status: 'partial', techStack: ['n8n', 'python'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/pricing-competitor', dependencies: ['listing-revise-price'], triggers: ['schedule-cron'], simpleExplain: 'ライバルの値段をチェックして自動で対抗', pythonScripts: ['competitor_scraper.py'] },
  { id: 'pricing-min-profit-guard', name: 'pricing-min-profit-guard', nameJp: '🛡️ 最低利益保証', description: '赤字になる価格設定を防止', category: 'pricing', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: false, hasAPI: true, hasDB: true, webhookPath: '/webhook/pricing-guard', dependencies: [], triggers: ['listing-reserve', 'pricing-dynamic'], simpleExplain: '絶対に赤字にならないようにストッパー', selfHealing: true },
  { id: 'pricing-currency-convert', name: 'pricing-currency-convert', nameJp: '💱 為替換算', description: '円/ドル/ユーロを自動換算', category: 'pricing', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: false, webhookPath: '/webhook/pricing-currency', dependencies: [], triggers: ['pricing-profit-calc'], simpleExplain: '今のレートでドル→円を計算' },
  { id: 'pricing-bulk-update', name: 'pricing-bulk-update', nameJp: '💵 一括価格変更', description: '複数商品の価格を一括で変更', category: 'pricing', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/pricing-bulk', dependencies: ['listing-revise-price'], triggers: [], simpleExplain: '100件の商品を一気に10%値上げとか' },
  { id: 'pricing-promotion', name: 'pricing-promotion', nameJp: '🎁 プロモーション価格', description: 'セール価格を設定', category: 'pricing', status: 'partial', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/pricing-promo', dependencies: [], triggers: [], simpleExplain: '期間限定セール価格を設定' },
  { id: 'pricing-history', name: 'pricing-history', nameJp: '📊 価格履歴', description: '価格変更の履歴を記録', category: 'pricing', status: 'active', techStack: ['n8n', 'sql'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/pricing-history', dependencies: [], triggers: ['listing-revise-price'], simpleExplain: 'いつ、いくらに変えたか記録' },
  { id: 'pricing-margin-report', name: 'pricing-margin-report', nameJp: '📈 利益率レポート', description: '商品ごとの利益率を分析', category: 'pricing', status: 'partial', techStack: ['n8n', 'sql'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/pricing-margin', dependencies: [], triggers: ['schedule-cron'], simpleExplain: '各商品の利益率を一覧で見る' },

  // === AI (ai) - 12件 ===
  { id: 'ai-enrich-product', name: 'ai-enrich-product', nameJp: '🤖 AI商品拡充', description: 'AIで商品情報を自動補完・拡充', category: 'ai', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['claude', 'gemini'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/ai-enrich', dependencies: [], triggers: [], simpleExplain: '画像と商品名から、AIが詳しい情報を補完', logic: '画像 + タイトル → Gemini分析 → Claude構造化' },
  { id: 'ai-image-analysis', name: 'ai-image-analysis', nameJp: '👁️ AI画像分析', description: '商品画像から特徴を抽出', category: 'ai', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['gemini'], hasUI: true, hasAPI: true, hasDB: false, webhookPath: '/webhook/ai-image', dependencies: [], triggers: ['ai-enrich-product'], simpleExplain: '画像を見て「これは青い陶器の花瓶」とか判定' },
  { id: 'ai-condition-grade', name: 'ai-condition-grade', nameJp: '📊 コンディション判定', description: 'AIで商品状態をグレーディング', category: 'ai', status: 'active', techStack: ['n8n', 'python'], aiComponents: ['claude', 'gemini'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/ai-condition', dependencies: [], triggers: [], simpleExplain: '写真を見て「これはNear Mint」とかグレードをつける', pythonScripts: ['psa_grader.py'] },
  { id: 'ai-psa-predict', name: 'ai-psa-predict', nameJp: '🎴 PSAグレード予測', description: 'カード写真からPSAグレードを予測', category: 'ai', status: 'partial', techStack: ['n8n', 'python'], aiComponents: ['gemini'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/ai-psa', dependencies: [], triggers: [], simpleExplain: 'ポケモンカードの写真からPSA何点か予測', pythonScripts: ['psa_grader.py'] },
  { id: 'ai-translate-listing', name: 'ai-translate-listing', nameJp: '🌐 AI翻訳', description: '商品情報を多言語翻訳', category: 'ai', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['claude'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/ai-translate', dependencies: [], triggers: [], simpleExplain: '日本語の商品説明を英語に自動翻訳' },
  { id: 'ai-inquiry-response', name: 'ai-inquiry-response', nameJp: '💬 AI問い合わせ対応', description: 'バイヤーからの問い合わせにAIが回答案を生成', category: 'ai', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['claude'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/ai-inquiry', dependencies: ['notify-chatwork'], triggers: [], simpleExplain: 'バイヤーからの質問にAIが返信案を作る', autoApproval: false },
  { id: 'ai-voice-generate', name: 'ai-voice-generate', nameJp: '🎙️ AI音声生成', description: 'ElevenLabsで音声を生成', category: 'ai', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['elevenlabs'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/ai-voice', dependencies: [], triggers: [], simpleExplain: 'テキストから人間っぽい音声を生成' },
  { id: 'ai-script-generate', name: 'ai-script-generate', nameJp: '📜 台本生成', description: '動画用の台本をAIが生成', category: 'ai', status: 'partial', techStack: ['n8n', 'typescript'], aiComponents: ['claude', 'gpt4'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/ai-script', dependencies: [], triggers: [], simpleExplain: 'YouTube動画用の台本をAIが書く' },
  { id: 'ai-thumbnail-generate', name: 'ai-thumbnail-generate', nameJp: '🖼️ AIサムネ生成', description: 'Midjourneyでサムネイルを生成', category: 'ai', status: 'partial', techStack: ['n8n', 'python'], aiComponents: ['midjourney'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/ai-thumbnail', dependencies: [], triggers: [], simpleExplain: 'AIが目を引くサムネイルを作る', pythonScripts: ['image_washer.py'] },
  { id: 'ai-price-suggest', name: 'ai-price-suggest', nameJp: '💡 AI価格提案', description: 'AIが最適な販売価格を提案', category: 'ai', status: 'partial', techStack: ['n8n', 'typescript'], aiComponents: ['gemini'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/ai-price', dependencies: [], triggers: [], simpleExplain: 'この商品いくらで売れそう？をAIが提案' },
  { id: 'ai-keyword-extract', name: 'ai-keyword-extract', nameJp: '🔑 キーワード抽出', description: 'AIがSEOキーワードを抽出', category: 'ai', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['claude'], hasUI: true, hasAPI: true, hasDB: false, webhookPath: '/webhook/ai-keyword', dependencies: [], triggers: [], simpleExplain: '商品説明から検索に強いキーワードを抽出' },
  { id: 'ai-fact-check', name: 'ai-fact-check', nameJp: '✅ ファクトチェック', description: '生成コンテンツの事実確認', category: 'ai', status: 'partial', techStack: ['n8n', 'typescript'], aiComponents: ['claude', 'gemini'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/ai-fact', dependencies: [], triggers: [], simpleExplain: 'AIが書いた内容が正しいかダブルチェック' },

  // === リサーチ (research) - 10件 ===
  { id: 'research-competitor', name: 'research-competitor', nameJp: '🔍 競合分析', description: '競合セラーの出品を分析', category: 'research', status: 'active', techStack: ['n8n', 'python'], aiComponents: ['gemini'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/research-competitor', dependencies: [], triggers: ['schedule-cron'], simpleExplain: 'ライバルがどんな商品をいくらで売ってるか分析', pythonScripts: ['competitor_scraper.py'] },
  { id: 'research-sold-analysis', name: 'research-sold-analysis', nameJp: '📊 売れ筋分析', description: 'eBay Sold Listingsを分析', category: 'research', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/research-sold', dependencies: [], triggers: ['schedule-cron'], simpleExplain: '最近何が売れてるか分析' },
  { id: 'research-profit-opportunity', name: 'research-profit-opportunity', nameJp: '💰 利ざや商品発見', description: '仕入れ価格と販売価格の差が大きい商品を発見', category: 'research', status: 'planned', techStack: ['n8n', 'python'], aiComponents: ['gemini'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/research-profit', dependencies: [], triggers: ['schedule-cron'], simpleExplain: '安く仕入れて高く売れる商品を自動で見つける' },
  { id: 'research-trend', name: 'research-trend', nameJp: '📈 トレンド分析', description: '市場トレンドを分析', category: 'research', status: 'partial', techStack: ['n8n', 'typescript'], aiComponents: ['gemini'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/research-trend', dependencies: [], triggers: ['schedule-cron'], simpleExplain: '今何が流行ってるかを分析' },
  { id: 'research-price-history', name: 'research-price-history', nameJp: '📉 相場履歴', description: '商品の価格推移を追跡', category: 'research', status: 'active', techStack: ['n8n', 'sql'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/research-price', dependencies: [], triggers: [], simpleExplain: 'この商品の値段が過去どう変わったか見る' },
  { id: 'research-niche-finder', name: 'research-niche-finder', nameJp: '🎯 ニッチ発見', description: '競争が少なく利益が出るニッチを発見', category: 'research', status: 'planned', techStack: ['n8n', 'python'], aiComponents: ['gemini'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/research-niche', dependencies: [], triggers: [], simpleExplain: 'ライバルが少なくて儲かるジャンルを見つける' },
  { id: 'research-keyword-rank', name: 'research-keyword-rank', nameJp: '🔤 キーワード順位', description: 'eBayでのキーワード検索順位を追跡', category: 'research', status: 'partial', techStack: ['n8n', 'python'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/research-keyword', dependencies: [], triggers: ['schedule-cron'], simpleExplain: '自分の商品が検索で何番目に出るかチェック' },
  { id: 'research-watch', name: 'research-watch', nameJp: '👀 ウォッチ監視', description: '特定商品の出品を監視', category: 'research', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/research-watch', dependencies: ['notify-chatwork'], triggers: ['schedule-cron'], simpleExplain: '欲しい商品が出たら通知' },
  { id: 'research-seasonality', name: 'research-seasonality', nameJp: '📅 季節性分析', description: '商品の季節需要を分析', category: 'research', status: 'planned', techStack: ['n8n', 'sql'], aiComponents: ['gemini'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/research-season', dependencies: [], triggers: [], simpleExplain: 'クリスマスに売れる商品とかを分析' },
  { id: 'research-report-generate', name: 'research-report-generate', nameJp: '📊 リサーチレポート', description: '分析結果をレポート化', category: 'research', status: 'partial', techStack: ['n8n', 'typescript'], aiComponents: ['claude'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/research-report', dependencies: [], triggers: [], simpleExplain: 'リサーチ結果をまとめたレポートを作る' },

  // === 防衛 (defense) - 8件 ===
  { id: 'defense-vero-check', name: 'defense-vero-check', nameJp: '🛡️ VERO確認', description: 'eBay VERO違反をチェック', category: 'defense', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/defense-vero', dependencies: [], triggers: ['listing-reserve'], simpleExplain: '出品禁止ブランドかチェック' },
  { id: 'defense-ban-monitor', name: 'defense-ban-monitor', nameJp: '⚠️ アカウント監視', description: 'アカウント制限兆候を監視', category: 'defense', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/defense-ban', dependencies: ['notify-chatwork'], triggers: ['schedule-cron'], simpleExplain: 'アカウント制限の兆候を警告' },
  { id: 'defense-defect-monitor', name: 'defense-defect-monitor', nameJp: '📊 Defect監視', description: 'eBay Defect率を監視', category: 'defense', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/defense-defect', dependencies: ['notify-chatwork'], triggers: ['schedule-cron'], simpleExplain: 'セラー評価をチェック' },
  { id: 'defense-ip-rotation', name: 'defense-ip-rotation', nameJp: '🔄 IPローテーション', description: 'プロキシIPを自動ローテーション', category: 'defense', status: 'partial', techStack: ['n8n', 'shell'], aiComponents: ['none'], hasUI: false, hasAPI: true, hasDB: true, webhookPath: '/webhook/defense-ip', dependencies: [], triggers: ['schedule-cron'], simpleExplain: 'BAN対策でIP定期変更' },
  { id: 'defense-fingerprint', name: 'defense-fingerprint', nameJp: '🆔 ブラウザ指紋', description: 'AdsPowerでブラウザ指紋を管理', category: 'defense', status: 'planned', techStack: ['n8n', 'python'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/defense-fingerprint', dependencies: [], triggers: [] },
  { id: 'defense-duplicate-check', name: 'defense-duplicate-check', nameJp: '🔍 重複出品チェック', description: '同一商品の重複出品を防止', category: 'defense', status: 'active', techStack: ['n8n', 'sql'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/defense-duplicate', dependencies: [], triggers: ['listing-reserve'], simpleExplain: '同じ商品を2回出品しないようチェック' },
  { id: 'defense-legal-update', name: 'defense-legal-update', nameJp: '📜 法改正監視', description: '輸出規制/法改正を監視', category: 'defense', status: 'planned', techStack: ['n8n'], aiComponents: ['gemini'], hasUI: false, hasAPI: true, hasDB: true, webhookPath: '/webhook/defense-legal', dependencies: ['notify-chatwork'], triggers: ['schedule-cron'] },
  { id: 'defense-rate-limiter', name: 'defense-rate-limiter', nameJp: '⏱️ レート制限', description: 'API呼び出しのレート制限管理', category: 'defense', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: false, hasAPI: true, hasDB: true, webhookPath: '/webhook/defense-rate', dependencies: [], triggers: [] },

  // === 同期 (sync) - 6件 ===
  { id: 'sync-ebay-inventory', name: 'sync-ebay-inventory', nameJp: '🔄 eBay在庫同期', description: 'eBay在庫をDBと同期', category: 'sync', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/sync-ebay', dependencies: [], triggers: ['schedule-cron'], simpleExplain: 'eBayとDBの在庫数を揃える', selfHealing: true },
  { id: 'sync-amazon-inventory', name: 'sync-amazon-inventory', nameJp: '🔄 Amazon在庫同期', description: 'Amazon在庫をDBと同期', category: 'sync', status: 'planned', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: false, hasAPI: false, hasDB: true, webhookPath: '/webhook/sync-amazon', dependencies: [], triggers: ['schedule-cron'] },
  { id: 'sync-orders-all', name: 'sync-orders-all', nameJp: '🔄 全注文同期', description: '全プラットフォームの注文を同期', category: 'sync', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/sync-orders', dependencies: ['orders-new'], triggers: ['schedule-cron'], selfHealing: true },
  { id: 'sync-policy', name: 'sync-policy', nameJp: '🔄 ポリシー同期', description: 'eBay Business Policyを同期', category: 'sync', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/sync-policy', dependencies: [], triggers: [] },
  { id: 'sync-category', name: 'sync-category', nameJp: '🔄 カテゴリ同期', description: 'eBayカテゴリマスタを同期', category: 'sync', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/sync-category', dependencies: [], triggers: ['schedule-cron'] },
  { id: 'sync-token-refresh', name: 'sync-token-refresh', nameJp: '🔑 トークン更新', description: 'OAuthトークンを自動更新', category: 'sync', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: false, hasAPI: true, hasDB: true, webhookPath: '/webhook/sync-token', dependencies: [], triggers: ['schedule-cron'], selfHealing: true, autoApproval: true },

  // === 通知 (notification) - 4件 ===
  { id: 'notify-chatwork', name: 'notify-chatwork', nameJp: '💬 ChatWork通知', description: 'ChatWorkにメッセージを送信', category: 'notification', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: false, webhookPath: '/webhook/notify-chatwork', dependencies: [], triggers: [] },
  { id: 'notify-email', name: 'notify-email', nameJp: '📧 メール通知', description: 'メールで通知を送信', category: 'notification', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: false, webhookPath: '/webhook/notify-email', dependencies: [], triggers: [] },
  { id: 'notify-slack', name: 'notify-slack', nameJp: '💬 Slack通知', description: 'Slackにメッセージを送信', category: 'notification', status: 'planned', techStack: ['n8n'], aiComponents: ['none'], hasUI: false, hasAPI: false, hasDB: false, webhookPath: '/webhook/notify-slack', dependencies: [], triggers: [] },
  { id: 'notify-daily-summary', name: 'notify-daily-summary', nameJp: '📊 日次サマリー', description: '1日の売上/出品サマリーを通知', category: 'notification', status: 'active', techStack: ['n8n', 'sql'], aiComponents: ['none'], hasUI: false, hasAPI: true, hasDB: true, webhookPath: '/webhook/notify-summary', dependencies: ['notify-chatwork'], triggers: ['schedule-cron'], autoApproval: true },

  // === 注文 (orders) - 10件 ===
  { id: 'orders-new', name: 'orders-new', nameJp: '📋 新規注文取込', description: 'eBay/Amazonから新規注文を取込', category: 'orders', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/orders-new', dependencies: ['notify-chatwork'], triggers: ['schedule-cron'], selfHealing: true },
  { id: 'orders-payment-confirm', name: 'orders-payment-confirm', nameJp: '💳 入金確認', description: '支払い完了を確認', category: 'orders', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/orders-payment', dependencies: [], triggers: ['orders-new'] },
  { id: 'orders-ship-notify', name: 'orders-ship-notify', nameJp: '📦 発送通知', description: 'バイヤーに発送完了を通知', category: 'orders', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/orders-ship', dependencies: [], triggers: ['shipping-label-create'] },
  { id: 'orders-cancel', name: 'orders-cancel', nameJp: '❌ 注文キャンセル', description: '注文をキャンセル処理', category: 'orders', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/orders-cancel', dependencies: ['inventory-sync-all'], triggers: [] },
  { id: 'orders-return', name: 'orders-return', nameJp: '↩️ 返品処理', description: '返品リクエストを処理', category: 'orders', status: 'partial', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/orders-return', dependencies: ['inventory-sync-all'], triggers: [] },
  { id: 'orders-invoice-generate', name: 'orders-invoice-generate', nameJp: '📄 インボイス作成', description: '注文のインボイスを自動生成', category: 'orders', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/orders-invoice', dependencies: [], triggers: ['orders-new'] },
  { id: 'orders-packing-list', name: 'orders-packing-list', nameJp: '📋 梱包リスト', description: '本日の梱包リストを生成', category: 'orders', status: 'active', techStack: ['n8n', 'sql'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/orders-packing', dependencies: [], triggers: ['schedule-cron'] },
  { id: 'orders-reminder', name: 'orders-reminder', nameJp: '⏰ 発送リマインダー', description: '未発送注文をリマインド', category: 'orders', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: false, hasAPI: true, hasDB: true, webhookPath: '/webhook/orders-reminder', dependencies: ['notify-chatwork'], triggers: ['schedule-cron'] },
  { id: 'orders-combine', name: 'orders-combine', nameJp: '📦 同梱処理', description: '同一バイヤーの注文を同梱', category: 'orders', status: 'partial', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/orders-combine', dependencies: [], triggers: [] },
  { id: 'orders-feedback-request', name: 'orders-feedback-request', nameJp: '⭐ フィードバック依頼', description: '到着後にフィードバックを依頼', category: 'orders', status: 'partial', techStack: ['n8n'], aiComponents: ['none'], hasUI: false, hasAPI: true, hasDB: true, webhookPath: '/webhook/orders-feedback', dependencies: [], triggers: ['schedule-cron'], autoApproval: true },

  // === 配送 (shipping) - 7件 ===
  { id: 'shipping-label-create', name: 'shipping-label-create', nameJp: '🏷️ 送り状作成', description: 'EMS/ePacketの送り状を作成', category: 'shipping', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/shipping-label', dependencies: ['orders-ship-notify'], triggers: [] },
  { id: 'shipping-tracking-update', name: 'shipping-tracking-update', nameJp: '📍 追跡更新', description: '追跡番号のステータスを更新', category: 'shipping', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/shipping-tracking', dependencies: [], triggers: ['schedule-cron'] },
  { id: 'shipping-delivered-confirm', name: 'shipping-delivered-confirm', nameJp: '✅ 配達完了確認', description: '配達完了を検出して処理', category: 'shipping', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: false, hasAPI: true, hasDB: true, webhookPath: '/webhook/shipping-delivered', dependencies: ['orders-feedback-request'], triggers: ['shipping-tracking-update'], autoApproval: true },
  { id: 'shipping-rate-compare', name: 'shipping-rate-compare', nameJp: '💰 送料比較', description: '各配送方法の料金を比較', category: 'shipping', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/shipping-rate', dependencies: [], triggers: [] },
  { id: 'shipping-bulk-print', name: 'shipping-bulk-print', nameJp: '🖨️ 一括印刷', description: '複数注文の送り状を一括印刷', category: 'shipping', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: false, webhookPath: '/webhook/shipping-bulk', dependencies: [], triggers: [] },
  { id: 'shipping-customs-form', name: 'shipping-customs-form', nameJp: '📋 税関書類', description: '税関申告書を自動生成', category: 'shipping', status: 'partial', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/shipping-customs', dependencies: [], triggers: ['shipping-label-create'] },
  { id: 'shipping-problem-detect', name: 'shipping-problem-detect', nameJp: '⚠️ 配送トラブル検出', description: '配送遅延/紛失を検出', category: 'shipping', status: 'partial', techStack: ['n8n'], aiComponents: ['none'], hasUI: false, hasAPI: true, hasDB: true, webhookPath: '/webhook/shipping-problem', dependencies: ['notify-chatwork'], triggers: ['schedule-cron'] },

  // === 財務 (finance) - 6件 ===
  { id: 'finance-sales-report', name: 'finance-sales-report', nameJp: '📊 売上レポート', description: '売上データをレポート化', category: 'finance', status: 'active', techStack: ['n8n', 'sql'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/finance-sales', dependencies: [], triggers: ['schedule-cron'] },
  { id: 'finance-profit-report', name: 'finance-profit-report', nameJp: '💰 利益レポート', description: '利益データをレポート化', category: 'finance', status: 'active', techStack: ['n8n', 'sql'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/finance-profit', dependencies: [], triggers: ['schedule-cron'] },
  { id: 'finance-expense-track', name: 'finance-expense-track', nameJp: '💸 経費追跡', description: '経費を記録・分類', category: 'finance', status: 'partial', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/finance-expense', dependencies: [], triggers: [] },
  { id: 'finance-payout-reconcile', name: 'finance-payout-reconcile', nameJp: '💵 入金照合', description: 'eBay/PayPalの入金を照合', category: 'finance', status: 'partial', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/finance-payout', dependencies: [], triggers: ['schedule-cron'] },
  { id: 'finance-tax-calc', name: 'finance-tax-calc', nameJp: '🏛️ 税金計算', description: '消費税/所得税を計算', category: 'finance', status: 'planned', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/finance-tax', dependencies: [], triggers: [] },
  { id: 'finance-invoice-export', name: 'finance-invoice-export', nameJp: '📄 請求書出力', description: '請求書をPDF出力', category: 'finance', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/finance-invoice', dependencies: [], triggers: [] },

  // === メディア (media) - 7件 ===
  { id: 'media-video-create', name: 'media-video-create', nameJp: '🎬 動画生成', description: 'Remotionで動画を自動生成', category: 'media', status: 'partial', techStack: ['n8n', 'typescript', 'python'], aiComponents: ['claude', 'elevenlabs'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/media-video', dependencies: ['ai-voice-generate'], triggers: [], pythonScripts: ['video_render.py', 'lip_sync.py'] },
  { id: 'media-thumbnail-create', name: 'media-thumbnail-create', nameJp: '🖼️ サムネ作成', description: '動画サムネイルを自動生成', category: 'media', status: 'partial', techStack: ['n8n', 'python'], aiComponents: ['midjourney'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/media-thumbnail', dependencies: [], triggers: ['media-video-create'], pythonScripts: ['image_washer.py'] },
  { id: 'media-youtube-upload', name: 'media-youtube-upload', nameJp: '📺 YouTube投稿', description: 'YouTubeに動画を自動投稿', category: 'media', status: 'planned', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/media-youtube', dependencies: ['media-video-create'], triggers: ['schedule-cron'] },
  { id: 'media-blog-generate', name: 'media-blog-generate', nameJp: '📝 ブログ生成', description: '動画からブログ記事を生成', category: 'media', status: 'partial', techStack: ['n8n', 'typescript'], aiComponents: ['claude'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/media-blog', dependencies: [], triggers: ['media-video-create'] },
  { id: 'media-ebook-generate', name: 'media-ebook-generate', nameJp: '📚 電子書籍生成', description: 'コンテンツを電子書籍化', category: 'media', status: 'planned', techStack: ['n8n', 'typescript'], aiComponents: ['claude'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/media-ebook', dependencies: [], triggers: [] },
  { id: 'media-sns-post', name: 'media-sns-post', nameJp: '📱 SNS投稿', description: 'Twitter/InstagramにSNS投稿', category: 'media', status: 'planned', techStack: ['n8n'], aiComponents: ['claude'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/media-sns', dependencies: [], triggers: ['media-video-create'] },
  { id: 'media-asset-library', name: 'media-asset-library', nameJp: '📂 アセット管理', description: '画像/音声アセットを管理', category: 'media', status: 'partial', techStack: ['n8n', 'sql'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/media-asset', dependencies: [], triggers: [] },

  // === 司令塔 (command) - 6件 ===
  { id: 'schedule-cron', name: 'schedule-cron', nameJp: '⏰ スケジュール実行', description: 'cron形式で定期実行を管理', category: 'command', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/schedule-cron', n8nWorkflowId: 'N3-SCHEDULE-CRON-COMPLETE', dependencies: [], triggers: [], selfHealing: true },
  { id: 'command-health-check', name: 'command-health-check', nameJp: '🏥 ヘルスチェック', description: 'システム全体の健全性を確認', category: 'command', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/command-health', dependencies: ['notify-chatwork'], triggers: ['schedule-cron'], selfHealing: true },
  { id: 'command-failover', name: 'command-failover', nameJp: '🔄 フェイルオーバー', description: '障害時に自動で復旧処理', category: 'command', status: 'partial', techStack: ['n8n', 'shell'], aiComponents: ['none'], hasUI: false, hasAPI: true, hasDB: true, webhookPath: '/webhook/command-failover', dependencies: ['notify-chatwork'], triggers: ['command-health-check'], selfHealing: true },
  { id: 'command-batch-runner', name: 'command-batch-runner', nameJp: '🚀 バッチ実行', description: '複数ワークフローを連続実行', category: 'command', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/command-batch', dependencies: [], triggers: [] },
  { id: 'command-queue-manager', name: 'command-queue-manager', nameJp: '📋 キュー管理', description: '処理キューを監視・管理', category: 'command', status: 'active', techStack: ['n8n', 'sql'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/command-queue', dependencies: [], triggers: ['schedule-cron'] },
  { id: 'command-emergency-stop', name: 'command-emergency-stop', nameJp: '🛑 緊急停止', description: '全ワークフローを緊急停止', category: 'command', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: false, webhookPath: '/webhook/command-stop', dependencies: ['notify-chatwork'], triggers: [] },

  // === システム (system) - 6件 ===
  { id: 'system-backup', name: 'system-backup', nameJp: '💾 バックアップ', description: 'DBをバックアップ', category: 'system', status: 'active', techStack: ['n8n', 'shell', 'sql'], aiComponents: ['none'], hasUI: false, hasAPI: true, hasDB: true, webhookPath: '/webhook/system-backup', dependencies: [], triggers: ['schedule-cron'], autoApproval: true },
  { id: 'system-log-cleanup', name: 'system-log-cleanup', nameJp: '🧹 ログクリーンアップ', description: '古いログを自動削除', category: 'system', status: 'active', techStack: ['n8n', 'sql'], aiComponents: ['none'], hasUI: false, hasAPI: true, hasDB: true, webhookPath: '/webhook/system-log', dependencies: [], triggers: ['schedule-cron'], autoApproval: true },
  { id: 'system-db-optimize', name: 'system-db-optimize', nameJp: '⚡ DB最適化', description: 'データベースを最適化', category: 'system', status: 'active', techStack: ['n8n', 'sql'], aiComponents: ['none'], hasUI: false, hasAPI: true, hasDB: true, webhookPath: '/webhook/system-optimize', dependencies: [], triggers: ['schedule-cron'], autoApproval: true },
  { id: 'system-error-report', name: 'system-error-report', nameJp: '🐛 エラーレポート', description: 'エラーをレポート化', category: 'system', status: 'active', techStack: ['n8n', 'sql'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/system-error', dependencies: ['notify-chatwork'], triggers: ['schedule-cron'] },
  { id: 'system-usage-monitor', name: 'system-usage-monitor', nameJp: '📊 使用量監視', description: 'API使用量/コストを監視', category: 'system', status: 'partial', techStack: ['n8n', 'sql'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: true, webhookPath: '/webhook/system-usage', dependencies: ['notify-chatwork'], triggers: ['schedule-cron'] },
  { id: 'system-deploy', name: 'system-deploy', nameJp: '🚀 デプロイ', description: 'システムを自動デプロイ', category: 'system', status: 'partial', techStack: ['n8n', 'shell'], aiComponents: ['none'], hasUI: true, hasAPI: true, hasDB: false, webhookPath: '/webhook/system-deploy', dependencies: ['notify-chatwork'], triggers: [] },

  // === 共通モジュール (module) - 5件 ===
  { id: 'module-error-handler', name: 'module-error-handler', nameJp: '🛠️ エラーハンドラー', description: '共通エラー処理モジュール', category: 'module', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: false, hasAPI: false, hasDB: false, dependencies: ['notify-chatwork'], triggers: [], selfHealing: true },
  { id: 'module-rate-limiter', name: 'module-rate-limiter', nameJp: '⏱️ レートリミッター', description: '共通レート制限モジュール', category: 'module', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: false, hasAPI: false, hasDB: true, dependencies: [], triggers: [] },
  { id: 'module-retry-logic', name: 'module-retry-logic', nameJp: '🔄 リトライロジック', description: '共通リトライ処理モジュール', category: 'module', status: 'active', techStack: ['n8n'], aiComponents: ['none'], hasUI: false, hasAPI: false, hasDB: false, dependencies: [], triggers: [], selfHealing: true },
  { id: 'module-auth-helper', name: 'module-auth-helper', nameJp: '🔐 認証ヘルパー', description: '共通認証処理モジュール', category: 'module', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: false, hasAPI: false, hasDB: true, dependencies: ['sync-token-refresh'], triggers: [] },
  { id: 'module-data-transformer', name: 'module-data-transformer', nameJp: '🔄 データ変換', description: '共通データ変換モジュール', category: 'module', status: 'active', techStack: ['n8n', 'typescript'], aiComponents: ['none'], hasUI: false, hasAPI: false, hasDB: false, dependencies: [], triggers: [] },
];

// ヘルパー関数
export function getWorkflowById(id: string): WorkflowNode | undefined {
  return WORKFLOW_REGISTRY.find(w => w.id === id);
}

export function getWorkflowsByCategory(category: WorkflowCategory): WorkflowNode[] {
  return WORKFLOW_REGISTRY.filter(w => w.category === category);
}

export function getWorkflowDependencies(id: string): WorkflowNode[] {
  const wf = getWorkflowById(id);
  if (!wf) return [];
  return wf.dependencies.map(d => getWorkflowById(d)).filter(Boolean) as WorkflowNode[];
}

export function getWorkflowTriggers(id: string): WorkflowNode[] {
  return WORKFLOW_REGISTRY.filter(w => w.triggers.includes(id));
}

export function getCategorySummary(): Array<{ category: WorkflowCategory; total: number; active: number; partial: number; planned: number }> {
  const cats = Object.keys(CATEGORY_CONFIG) as WorkflowCategory[];
  return cats.map(cat => {
    const wfs = getWorkflowsByCategory(cat);
    return { category: cat, total: wfs.length, active: wfs.filter(w => w.status === 'active').length, partial: wfs.filter(w => w.status === 'partial').length, planned: wfs.filter(w => w.status === 'planned').length };
  }).filter(s => s.total > 0);
}

export function generateMarkdownExport(): string {
  const now = new Date().toISOString().split('T')[0];
  let md = `# N3 Empire OS - 神経系マニュアル\n\n生成日: ${now}\n\n`;
  const cats = Object.keys(CATEGORY_CONFIG) as WorkflowCategory[];
  for (const cat of cats) {
    const cfg = CATEGORY_CONFIG[cat];
    const wfs = getWorkflowsByCategory(cat);
    if (wfs.length === 0) continue;
    md += `## ${cfg.icon} ${cfg.label} (${wfs.length}件)\n\n`;
    for (const w of wfs) {
      const st = w.status === 'active' ? '✅' : w.status === 'partial' ? '⚠️' : '📋';
      md += `### ${st} ${w.nameJp}\n- ID: \`${w.id}\`\n- ${w.description}\n`;
      if (w.simpleExplain) md += `- かんたん: ${w.simpleExplain}\n`;
      md += `\n`;
    }
  }
  return md;
}

export default WORKFLOW_REGISTRY;
